CONFIG_NAME: devnet
PRESET_BASE: mainnet

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
# Friday, April 22, 2022 9:00:00 AM +UTC
MIN_GENESIS_TIME: 1706718241
GENESIS_FORK_VERSION: 0x20000089
GENESIS_DELAY: 0

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092

# Deneb
# DENEB_FORK_EPOCH: 5
DENEB_FORK_VERSION: 0x20000093

# EIP4844
# EIP4844_FORK_EPOCH: 5
# EIP4844_FORK_VERSION: 0x20000093

TERMINAL_TOTAL_DIFFICULTY: 0
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 4
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 4
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 4
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 16

SLOTS_PER_EPOCH: 6

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Deposit contract
DEPOSIT_CHAIN_ID: 1234
DEPOSIT_NETWORK_ID: 1234
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
