version: "3.8"
services:
  lighthouse-beacon-chain:
    image: sigp/lighthouse
    volumes:
      - ../consensus/beacondata-lighthouse:/root/.lighthouse
      - ../config:/config
    ports:
      - 9100:9100
      - 5002:5002
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/config/jwtsecret
      - --testnet-dir=/config
      - --disable-peer-scoring
      - --disable-packet-filter
      - --http-allow-sync-stalled
      - --http
      - --http-address=0.0.0.0
      - --http-port=5002
      - --http-allow-origin=*
      - --gui
      - --eth1
      - --target-peers=1
      - --enr-address=0.0.0.0
      - --enr-udp-port=9100
      - --enr-tcp-port=9100
      - --port=9100
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: custom_network