version: "3.8"
services:
  lighthouse-beacon-chain:
    image: sigp/lighthouse
    volumes:
      - ../consensus/beacondata-lighthouse:/root/.lighthouse
      - ../config:/config
    ports:
      - 9100:9100
      - 5002:5002
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/config/jwtsecret
      - --testnet-dir=/config
      - --disable-peer-scoring
      - --disable-packet-filter
      - --http-allow-sync-stalled
      - --http
      - --http-address=0.0.0.0
      - --http-port=5002
      - --http-allow-origin=*
      - --gui
      - --eth1
      - --target-peers=1
      - --enr-address=lighthouse-beacon-chain
      - --enr-udp-port=9100
      - --enr-tcp-port=9100
      - --port=9100
      - --boot-nodes=enr:-MS4QMM8bxICEbuuYd3kKm1Ylconl3Lvg69qjSY2KQybGVgQFwzkFa_MJnJA5abPHvD0PjfpwL3jBQtOjXZbuRHbdX0Dh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAg6spDUAAAACBOAAAAAAAAgmlkgnY0gmlwhKwTAAaEcXVpY4Ij8YlzZWNwMjU2azGhA3XEa2iFTJfe8cNA2ZawJJP-qhOeJLwxkgHN8KHb1XfniHN5bmNuZXRzAIN0Y3CCI_CDdWRwgiPw
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: custom_network