version: "3.8"
services:
  lighthouse-beacon-chain2:
    image: sigp/lighthouse
    volumes:
      - ../consensus/beacondata-lighthouse2:/root/.lighthouse
      - ../config:/config
    ports:
      - 9200:9200
      - 5102:5102
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://geth2:9551
      - --execution-jwt=/config/jwtsecret
      - --testnet-dir=/config
      - --disable-peer-scoring
      - --disable-packet-filter
      - --http-allow-sync-stalled
      - --http
      - --http-address=0.0.0.0
      - --http-port=5102
      - --http-allow-origin=*
      - --gui
      - --eth1
      - --target-peers=1
      - --enr-address=lighthouse-beacon-chain2
      - --enr-udp-port=9200
      - --enr-tcp-port=9200
      - --port=9200
      - --boot-nodes=enr:-MS4QKGfaQHUIvxZLPewfSmbuY43zOxORqiTId_EIEXdWOD5YooVbuopo4rCYofhMk96Aup_OUW3LNDbgAh_oMYdBSg7h2F0dG5ldHOIAAAAAAAYAACEZXRoMpAg6spDUAAAACBOAAAAAAAAgmlkgnY0gmlwhKwXAASEcXVpY4IjjYlzZWNwMjU2azGhA7Pa6ijEhFYowZYz_eMRjQt-7l2gH3o8baYugdP2OYpmiHN5bmNuZXRzD4N0Y3CCI4yDdWRwgiOM,enr:-MS4QHjjWfXnPk24EJ_ri6T6c3xXth5FNAub1cqNyEGHC8YucCqt6_O5pdVEPxLFYjkwzPqAY_m8efhe9ZydzsD2oG8Kh2F0dG5ldHOIAQAAAAAAAICEZXRoMpAg6spDUAAAACBOAAAAAAAAgmlkgnY0gmlwhKwXAAaEcXVpY4IkVYlzZWNwMjU2azGhAvobuEvYSnWRB6znL8YrwmmpdCbljAhX-z9HhctTM09GiHN5bmNuZXRzAIN0Y3CCJFSDdWRwgiRU
      - --purge-db
      - --checkpoint-sync-url=http://lighthouse-beacon-chain:5002
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: custom_network